### ISSUE TITLE
breaks in AWS lambda

### ISSUE THREAD

**Issue by cphoover** [TheDeveloper/http-aws-es#11]
the inclusion of aws-sdk will break in a lambda environment. Lambda injects it's own copy of aws-sdk which it requires you to use. I've made my own copy of this library that allows for the aws-sdk to be injected: https://github.com/cphoover/http-aws-es-di

not the cleanest solution but allows me to use this library in a lambda environment.

**Comment by TheDeveloper** [comment]
@cphoover ah yes I saw your fork at the weekend. Thanks for the info about it.

Some work is needed to make this connector work better on Lambda, as #1 points out too.

This is a good idea. A future version of this module could support passing an instance of aws-sdk like you have done.

**Comment by mt-sergio** [comment]
+1 to this feature. `aws-sdk` package's size is 16Mb.

**Comment by duhseekoh** [comment]
I haven't had any issues working in a lambda environment. The aws-sdk is already installed in lambda environment, no need to package it up. http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html
