### ISSUE TITLE
Does this work with instance profiles?

### ISSUE THREAD

**Issue by thedug** [TheDeveloper/http-aws-es#14]
There 2 examples shown

1) using hard coded keys
2j using a named profile

Is it possible to use the default profile from an instance profile?

**Comment by thedug** [comment]
I got it to work if I wrapped everything with a refresh.

Does it make sense to refresh the credentials within the http-aws-es module?

```
var AWS = require('aws-sdk');

var myCredentials = new AWS.EC2MetadataCredentials();
myCredentials.refresh(function(){ ... })
```

**Comment by jtornblad** [comment]
Having difficulty dealing with expiration / rotation of EC2MetadataCredentials on an instance running under an instance profile / role.  This code works well to initialize the client with the proper credentials "the first" time after asynchronous fetching of the credentials from EC2 metadata:

```
var es = {}
var credentials = new AWS.EC2MetadataCredentials();
credentials.refresh(function(err) {
  if(err) throw err;
  es = require('elasticsearch').Client({
    host: '...endpoint...',
    connectionClass: require('http-aws-es'),
    amazonES: {
      region: 'us-east-1',
      credentials: credentials
    }
  })
})
```

But after the credentials initialized (and copied around in?) the client expire / are rotated, how to refresh them in the client?  There doesn't appear to be any automatic retry / refresh.  Is this possible?

**Comment by awolden** [comment]
I got this to work with EC2 instances by wrapping the request and checking for expired creds on every request.

```
const credentials = new aws.EC2MetadataCredentials();

const esClient = new es.Client({
  host: config.esEndPoint,
  log: 'info',
  connectionClass: (!isDev) ? require('http-aws-es') : undefined,
  amazonES: {
    region: process.env.EC2_REGION,
    credentials
  }
});

function performQuery(index, body) {
  return refreshAwsCreds(esClient, credentials)
    .then(() =>
      esClient.search({
        index,
        type: index,
        body,
      })
    );
}

function refreshAwsCreds(client, awsCreds) {
  if (isDev || !awsCreds.needsRefresh()) return Promise.resolve();
  return new Promise((resolve, reject) => {
    awsCreds.refresh((err) => {
      if (err) return reject(err);
      client.creds = awsCreds;
      resolve();
      console.log('Refreshed AWS Credentials', esClient.creds);
    });
  });
}
```

**Comment by jtornblad** [comment]
Thanks!  Will try this out.
