### ISSUE TITLE
Register Snapshot

### ISSUE THREAD

**Issue by christopherjbaker** [TheDeveloper/http-aws-es#18]
I am using elasticsearch 11.0.1 with http-aws-es 1.1.3, connecting to ES 2.3. The setup work perfectly for updating mapping, searching, etc, so I know that portion is set up correctly.

I am trying to register a snapshot repository on s3, and am following along at http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-snapshots and have set up all permissions/buckets/etc as instructed. I am using the "snapshot.createRepository" method, as detailed at https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference-2-3.html#api-snapshot-createrepository-2-3 . I have spent quite some time searching, and only found people asking the same question, or solutions that involve the yml config files, which are inaccessible as this is the hosted service.

Do you have any suggestions? I only ask here, as this is how the permissions are being made available to the ES client, and would think that is also how they would be made available for this.

Code and Error follow.

```javascript
client.snapshot.createRepository({
	repository: 'backup-s3',
	body: {
		type: 's3',
		settings: {
			bucket: 'interkn-elasticsearch-backup',
			region: 'us-west-2',
			role_arn: 'arn:aws:iam::XXX:role/elasticsearch-backup',
		},
	},
});
```

```json
{
    "error":{
        "root_cause":[
            {
                "type":"repository_exception",
                "reason":"[backup-s3] failed to create repository"
            }
        ],
        "type":"repository_exception",
        "reason":"[backup-s3] failed to create repository",
        "caused_by":{
            "type":"creation_exception",
            "reason":"Guice creation errors:\n\n1) Error injecting constructor, com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain\n  at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)\n  while locating org.elasticsearch.repositories.s3.S3Repository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error",
            "caused_by":{
                "type":"amazon_client_exception",
                "reason":"Unable to load AWS credentials from any provider in the chain"
            }
        }
    },
    "status":500
}
```

**Comment by JamesrenaudMitel** [comment]
@christopherjbaker what was your solution for this? I'm attempting to do exactly the same thing and not having a whole lot of luck. Any chance you can share some code?

**Comment by christopherjbaker** [comment]
It wasn't a code issue, it was just a permissions issue. Make sure you follow all the instructions on the page.
