### ISSUE TITLE
Can this be used behind a proxy?

### ISSUE THREAD

**Issue by sean256** [TheDeveloper/http-aws-es#25]
When I'm behind my companies http proxy the elastic connections timeout, otherwise it works fine.

**Comment by TheDeveloper** [comment]
Hi @sean256, you can now set httpOptions.proxy in the module's settings. Perhaps this might help?

**Comment by sean256** [comment]
Wow, that's awesome. That may work, but our company JUST switched to a transparent proxy, as in today. So I don't have any easy way to test this.

**Comment by TheDeveloper** [comment]
Hi @sean256 - is there anything more you would like to discuss here or can we close this issue?
