### ISSUE TITLE
Handle AWS credential  retrieval failure nicely

### ISSUE THREAD

**Issue by haoliangyu** [TheDeveloper/http-aws-es#35]
Currently there is no error handling for the function `getAWSCredentials()`. If it fails to retrieve the AWS credential, it will simply print the following message in the console.

``` bash
(node:17597) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
TypeError: Data must be a string or a buffer
(node:17597) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the 
future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit 
code.
```

It doesn't throw an error with a complete failure stacktrace and stop the program from running further even though the ES initialization completely fails. Because of this failure, if the user continue to use ES, he will always get a time-out error.

**Comment by TheDeveloper** [comment]
Hi, thanks for the report and the details.

Agreed, should be handling this better.

**Comment by pradyumna1** [comment]
This isn't fixed yet I guess.
