### ISSUE TITLE
Multiple ES connections?

### ISSUE THREAD

**Issue by sradu** [TheDeveloper/http-aws-es#37]
I upgraded to version 2.0 and I'm unclear as how to to create multiple objects to different regions (with different credentials).

For regular AWS objects I can use things like:
````
const one = new AWS.S3({ region: 'us-east-1' })
const two = new AWS.S3({ region: 'us-west-1' })
````

**Comment by TheDeveloper** [comment]
The connector now makes use of the global AWS object so it can use its default credential loading behaviour (through the provider chain to check various sources such as the environment).

This has the side effect that each instance of the connector will use the same global AWS configuration.

We could re-introduce the ability to pass in your own credentials object to allow separate AWS configs per instance.

Would this address your requirements @sradu?

Are you connecting to two different Amazon ES endpoints in different regions within the same process?

**Comment by sradu** [comment]
Yes on both counts. It would solve our issues.

We are connecting to Amazon ES in different regions.

**Comment by sradu** [comment]
Thank you!
