### ISSUE TITLE
Missing dependency to aws-sdk

### ISSUE THREAD

**Issue by jbenoit2011** [TheDeveloper/http-aws-es#4]
I encounter this error : `Cannot find module 'aws-sdk'`
It appears there is no dependency to `aws-sdk` in the package.json.
Since, the connector uses `aws-sdk`, it must declare the dependency to it.
I can do a PR if you want.

**Comment by TheDeveloper** [comment]
Correct. For now you should have `aws-sdk` already installed in your project.

I don't see any reason why I shouldn't add it to this module's package.json though.

**Comment by TheDeveloper** [comment]
Merged #5
