### ISSUE TITLE
Unable to get module to work from browser

### ISSUE THREAD

**Issue by HumanistSerif** [TheDeveloper/http-aws-es#42]
This might be more of a request than an issue.

Does this module work from within the browser? I don't have a NodeJS app and I'm trying to execute this script from within the browser. I'm using Browserify to require and bundle the necessary modules. 

```
var AWS = require('aws-sdk');
var creds = new AWS.Credentials('AKID','Security');
var  es = require('elasticsearch').Client({
    host: 'https://hostname.us-east-1.es.amazonaws.com/',
    connectionClass: require('http-aws-es'),
    amazonES: {
      region: 'us-east-1',
      credentials: creds
    }
  });

es.cluster.health({},function(err,resp,status) {
    console.log("-- Client Health --",resp);
});
```

I get the following error in the console:

`AWS Credentials error: No credentials to load`

Is it possible to adapt this awesome module to work from within the browser?

**Comment by TheDeveloper** [comment]
Hi @HumanistSerif 

This should work fine in the browser. That config you're using there is for an older version of this module. Perhaps try upgrading and taking a look at the readme for configuring the latest version?

**Comment by TheDeveloper** [comment]
Actually, I take that back. This probably won't play nice with browsers at the moment because the connector tries to use `AWS.NodeHTTPClient` which will not be available in a browserified `aws-sdk`.

It should be possible to add in support for running in browsers. We would need to use the `AWS.XHRClient` instead.

**Comment by TheDeveloper** [comment]
@HumanistSerif just pushed 4.0.0 for ability to run in browsers. Please re-open this issue if any problems.
