### ISSUE TITLE
`aws-sdk` in devDependencies

### ISSUE THREAD

**Issue by stpnvntn** [TheDeveloper/http-aws-es#55]
Is it ok that `aws-sdk` in devDependencies instead of Dependencies?

https://github.com/TheDeveloper/http-aws-es/blob/5099705b10afd65944f300f1c3b73025edcc1283/package.json#L24-L25

**Comment by compwright** [comment]
@stpnvntn Yes, it is in `peerDependencies` which will cause NPM to prompt you to install `aws-sdk` on your own. The reason for this is that other libraries might also be present that need some version of `aws-sdk` so it helps to prevent version conflicts or duplicate copies.

The reason it is in `devDependencies` is for testing purposes.
