### ISSUE TITLE
Support for @elastic/elasticsearch client API

### ISSUE THREAD

**Issue by mohitkhanna** [TheDeveloper/http-aws-es#67]
Hello All,

Just noticed that latest client API by Elastic installed via `npm install @elastic/elasticsearch` does not have `connectionClass` attribute while creating the client object. This break `http-aws-es` signing of requests for AWS hosted ES.

Any idea how to support the latest Client API. Is there a fork of this already out there?

Latest ES Client API: https://github.com/elastic/elasticsearch-js

Though the Readme of this library mentions supporting it - but internally uses the legacy library "elasticsearch" in package.json.

**Comment by compwright** [comment]
Duplicate of #63

**Comment by mohitkhanna** [comment]
Thank you @compwright. Will check out issue #63
