### ISSUE TITLE
Not able to resolve elasticsearch dependency | Node version 15.6.0

### ISSUE THREAD

**Issue by prashantraghav** [TheDeveloper/http-aws-es#82]
npm install http-aws-es
[..................] / idealTree:snapshot: sill idealTree buildDeps
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: snapshot@0.0.1
npm ERR! Found: elasticsearch@16.7.2
npm ERR! node_modules/elasticsearch
npm ERR! elasticsearch@"^16.7.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer elasticsearch@"^15.0.0" from http-aws-es@6.0.0
npm ERR! node_modules/http-aws-es
npm ERR! http-aws-es@"^6.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-01-19T14_38_27_204Z-debug.log

event if i try --force the error is same.

**Comment by jwhance** [comment]
It appears that this repo is effectively abandoned although this is a very useful package.  

I forked this repo, updated the elasticsearch dependency, and re-published it to npm.  Please feel free to try it:

https://www.npmjs.com/package/@jwhance/http-aws-es

It did still pass the tests after updating but there are not that many tests.  I tried it with my application and it works as expected.  Please let me know if you find any issues and I'll try to resolve them.

**Comment by TheDeveloper** [comment]
Hi, there is a new version of this module available here: https://github.com/gosquared/aws-elasticsearch-js
