### ISSUE TITLE
Local

### ISSUE THREAD

**Issue by pontusab** [TheDeveloper/http-aws-es#9]
Hi, is it possible to run this in local environment?

**Comment by TheDeveloper** [comment]
So long as you have an Amazon ES endpoint to connect to this can run anywhere.

Are you thinking specifically about testing or local mocking?

**Comment by pontusab** [comment]
Okey, i have an docker ES running on "http://192.168.99.100:9200" and with the Connection handler i get "No living connections", but if don't include it in the client everything works. Do i need something else to make this work?

**Comment by TheDeveloper** [comment]
This won't work against a plain Elasticsearch instance. You only need to use this connection handler if you want to connect to Amazon Elasticsearch.

**Comment by pontusab** [comment]
I thought so too. Thanks.
